name: Update Version

on:
  push:
    branches: [ main ]

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update version file
      run: |
        echo "{\"version\": \"$(date +%Y%m%d.%H%M)\"}" > version.json
        cat version.json  # Debug: Print the contents of the file to the log

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add version.json
        git diff-index --quiet HEAD || git commit -m "Update version file"
        git push
